account:
  uin: 0
  password: ""
  encrypt: false
  login_protocol: 2
  protocol: 2
  auto_login: true
  use_sso_address: true
  data_dir: ./data

servers:
  - http:
      host: 0.0.0.0
      port: 5700
      post:
        - url: http://nonebot:8080/
      access_token: ""
      secret: ""
    ws:
      host: 0.0.0.0
      port: 6700
